#!/usr/bin/env python3
"""Regenerate mechanical skill materials from an OpenAPI document.

Reads ``skill/openapi.snapshot.json`` (or ``--url`` / ``--openapi``) and writes
``skill/generated-skill.md`` and ``skill/curl-reference.md``.

Verify mode (default in CI):

    python harness-ui/scripts/regenerate-skill-materials.py --check

Refresh committed outputs after API changes:

    python harness-ui/scripts/regenerate-skill-materials.py --write
    # or refresh the snapshot from a running server:
    python harness-ui/scripts/regenerate-skill-materials.py --write \\
        --url http://127.0.0.1:8085/v3/api-docs
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILL_DIR = ROOT / "skill"
DEFAULT_OPENAPI = SKILL_DIR / "openapi.snapshot.json"
GENERATED_SKILL = SKILL_DIR / "generated-skill.md"
CURL_REFERENCE = SKILL_DIR / "curl-reference.md"
BASE_URL = "http://127.0.0.1:8085"


def _ensure_harness() -> None:
    repo = ROOT.parent
    src = repo / "src"
    if src.is_dir() and str(src) not in sys.path:
        sys.path.insert(0, str(src))


def _load_spec(source: Path | str) -> object:
    _ensure_harness()
    from harness.engine.generate import load_spec

    return load_spec(source)


def _render(spec: object) -> tuple[str, str]:
    from harness.engine.axes import DocBudget
    from harness.engine.generate import curl_reference, skill_markdown

    base = BASE_URL.rstrip("/")
    curl = curl_reference(spec, DocBudget.VERBOSE, base_url=base)
    skill = skill_markdown(spec, DocBudget.VERBOSE, progressive=False)
    header = (
        "<!-- Generated by scripts/regenerate-skill-materials.py — do not edit. -->\n\n"
    )
    return header + skill + "\n", header + curl + "\n"


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _check(path: Path, expected: str) -> list[str]:
    if not path.is_file():
        return [f"missing {path.relative_to(ROOT)}"]
    actual = path.read_text(encoding="utf-8")
    if actual != expected:
        return [f"stale {path.relative_to(ROOT)} — run with --write"]
    return []


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--openapi", type=Path, help="OpenAPI JSON/YAML file")
    parser.add_argument("--url", help="Fetch OpenAPI from a running server")
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write outputs (and snapshot when --url is used)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if committed outputs differ from regeneration",
    )
    args = parser.parse_args()

    if args.url:
        spec = _load_spec(args.url)
        if args.write:
            import urllib.request

            with urllib.request.urlopen(args.url, timeout=30) as resp:  # noqa: S310
                snapshot = json.loads(resp.read().decode())
            _write(DEFAULT_OPENAPI, json.dumps(snapshot, indent=2, sort_keys=True) + "\n")
    elif args.openapi:
        spec = _load_spec(args.openapi)
    elif DEFAULT_OPENAPI.is_file():
        spec = _load_spec(DEFAULT_OPENAPI)
    else:
        print(f"no OpenAPI source; provide --url, --openapi, or {DEFAULT_OPENAPI}", file=sys.stderr)
        return 2

    skill_text, curl_text = _render(spec)

    if args.write:
        _write(GENERATED_SKILL, skill_text)
        _write(CURL_REFERENCE, curl_text)
        print(f"wrote {GENERATED_SKILL.relative_to(ROOT)}")
        print(f"wrote {CURL_REFERENCE.relative_to(ROOT)}")
        return 0

    if args.check or not args.write:
        errors = _check(GENERATED_SKILL, skill_text) + _check(CURL_REFERENCE, curl_text)
        if errors:
            for err in errors:
                print(err, file=sys.stderr)
            return 1
        print("skill materials are up to date")
        return 0

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
